export const textStyles = {
  h1: {
    fontSize: {
      _: "42px",
      xs: "48px",
      sm: "51px",
      md: "51px",
      lg: "72px",
      xxl: "88px",
    },
    fontWeight: "bold",
    letterSpacing: "-0.015em",
    fontFamily: "var(--fractul-alt-bold)",
  },
  h2: {
    fontSize: {
      _: "31px",
      xs: "31px",
      sm: "42px",
      md: "42px",
      lg: "45px",
      xxl: "60px",
    },
    fontWeight: "bold",
    letterSpacing: "-0.005em",
    fontFamily: "var(--fractul-alt-bold)",
  },
  h3: {
    fontSize: {
      _: "24px",
      xs: "24px",
      sm: "30px",
      md: "30px",
      lg: "30px",
      xxl: "36px",
    },
    fontWeight: "bold",
    letterSpacing: "-0.015em",
    fontFamily: "var(--fractul-alt-bold)",
  },
  subtitle1: {
    fontSize: {
      _: "23px",
      xs: "23px",
      sm: "23px",
      md: "23px",
      lg: "25px",
      xxl: "34px",
    },
    fontWeight: "normal",
    letterSpacing: "0.0025em",
    fontFamily: "var(--fractul-regular)",
  },
  subtitle2: {
    fontSize: {
      _: "16px",
      xs: "16px",
      sm: "16px",
      md: "16px",
      lg: "18px",
      xxl: "24px",
    },
    fontWeight: "bold",
    letterSpacing: "0.0025em",
    fontFamily: "var(--fractul-regular)",
  },
  body: {
    fontSize: {
      _: "16px",
      xs: "16px",
      sm: "16px",
      md: "16px",
      lg: "16px",
      xxl: "24px",
    },
    fontWeight: "normal",
    letterSpacing: "-0.008em",
    fontFamily: "var(--fractul-regular)",
  },
  caption: {
    fontSize: {
      _: "12px",
      xs: "12px",
      sm: "12px",
      md: "12px",
      lg: "12px",
      xxl: "16px",
    },
    fontWeight: "normal",
    letterSpacing: "0.004em",
    fontFamily: "var(--fractul-regular)",
  },
  overline: {
    fontSize: {
      _: "12px",
      xs: "12px",
      sm: "12px",
      md: "12px",
      lg: "12px",
      xxl: "16px",
    },
    fontWeight: "normal",
    letterSpacing: "0.015em",
    fontFamily: "var(--fractul-regular)",
    textTransform: "uppercase",
  },
};
